### PR TITLE
[Feature] Add system_clipboard copy mode

### PR DESCRIPTION
**Pull request by PairZhu**
1. Refactor the code for serializing the Shape class
2. Support for copying graphics using the system clipboard

### CODE REVIEW

**Comment by PairZhu** [comment]
Since I don't have a compilation environment for Qt multilingual tools, I didn't make a GUI configuration for this item, so I can help you add it if you think it's necessary.

**Comment by PairZhu** [comment]
@CVHub520 What about this PR

**Comment by CVHub520** [comment]
> @CVHub520 What about this PR


@PairZhu, appreciate your contribution! I'd kindly ask you to rebase the pull request against the most recent main branch. After you've done that, I'll be ready to merge it in. Just to flag, the Shape struct has been updated with additional fields, including kie_linking, so please take these into account. Additionally, watch out for any other modifications that have been made. If you can push the updates today, I'll make sure to review and merge them promptly.

**Review by CVHub520 — COMMENTED** [review]
All checks passed, LGTM!

**Comment by PairZhu** [comment]
> All checks passed, LGTM!

Not finished yet

**Comment by CVHub520** [comment]
Hey @PairZhu, I realized that I accidentally merged your PR even though it wasn't fully completed yet. I've rolled back the merge to prevent any issues. Could you please either create a new PR based on the updated branch or make the necessary modifications to the existing PR, ensuring that all the work is fully done? Thanks a lot for your understanding and cooperation.

**Comment by PairZhu** [comment]
Don't worry, I just haven't added the corresponding action yet.

**Comment by CVHub520** [comment]
That sounds great. If you have the time, would you mind completing it and then resubmitting the changes? Thank you once again for your generous contribution!

**Comment by PairZhu** [comment]
Done. Could you help recompile the translation file? @CVHub520

**Pull request merged**
