### PR TITLE
[Bug fix]: Auto trigger some new actions

### PR DESCRIPTION
**Pull request by PairZhu**
The "show_labels" and "show_texts" configuration items do not load the local configuration correctly when they are first opened, and the corresponding slot functions have some unnecessary code operations.

### CODE REVIEW

**Comment by PairZhu** [comment]
@CVHub520 Can you help review it sometime?

**Comment by CVHub520** [comment]
> @CVHub520 Can you help review it sometime?

Hey there! @PairZhu,

Thank you for submitting this pull request! I appreciate your effort in adding the `auto_trigger` functionality to the `new_action` function.

However, I have a few concerns about automatically triggering actions upon creation. Typically, actions are triggered by user interactions or specific events within the application. Automatically executing slot functions might lead to unexpected behavior, especially if the application's state is not ready for the action to be performed.

Additionally, I wanted to let you know that our project is currently in an active development phase, with frequent updates and changes. This means that there’s a higher likelihood of merge conflicts arising from contributions at this time.

Given this, it might be more practical to wait until we’re closer to a release to consider integrating new features. This way, we can avoid the inconvenience of dealing with repeated merge conflicts and ensure that new features are integrated smoothly with the latest version of the codebase.

We truly appreciate your willingness to contribute and your patience with our development process. Once we’re ready for new feature integration, we’ll be more than happy to revisit your pull request and work with you to get it merged.

Thank you for your understanding and continued support of our project!

**Comment by PairZhu** [comment]
> > @CVHub520 Can you help review it sometime?
> 
> Hey there! @PairZhu,
> 
> Thank you for submitting this pull request! I appreciate your effort in adding the `auto_trigger` functionality to the `new_action` function.
> 
> However, I have a few concerns about automatically triggering actions upon creation. Typically, actions are triggered by user interactions or specific events within the application. Automatically executing slot functions might lead to unexpected behavior, especially if the application's state is not ready for the action to be performed.
> 
> Additionally, I wanted to let you know that our project is currently in an active development phase, with frequent updates and changes. This means that there’s a higher likelihood of merge conflicts arising from contributions at this time.
> 
> Given this, it might be more practical to wait until we’re closer to a release to consider integrating new features. This way, we can avoid the inconvenience of dealing with repeated merge conflicts and ensure that new features are integrated smoothly with the latest version of the codebase.
> 
> We truly appreciate your willingness to contribute and your patience with our development process. Once we’re ready for new feature integration, we’ll be more than happy to revisit your pull request and work with you to get it merged.
> 
> Thank you for your understanding and continued support of our project!

This PR is actually intended to fix a bug, not to add new features. Currently, some configurations (such as show_labels) are not loading correctly. There is no difference between automatically triggering and manually calling the slot function once; similar operations already exist in the original code. The newly added auto-trigger actions only require the canvas to complete initialization before execution, and they do not produce side effects. Since the canvas initialization occurs above the action definitions, this modification is safe.

**Comment by CVHub520** [comment]
Thank you for your patience and for the detailed explanation, @PairZhu. This PR looks very promising and I appreciate the effort you've put into addressing the bug with configuration loading.

I understand now that the `auto_trigger` functionality is intended to ensure proper initialization rather than adding new features. Given your clarification that the auto-trigger actions are safe and do not produce side effects, I'm more comfortable with the approach.

Would you mind resolving the code conflicts so that we can proceed with merging this PR? Once the conflicts are resolved, I'll be happy to merge it into the main codebase.

Thank you again for your contribution and for working through this with us! We're grateful for your support. 🚀

**Comment by CVHub520** [comment]
Hi @PairZhu,

I noticed that there is a conflict with the latest branch. Could you please pull the latest changes from the main branch and make the necessary modifications to resolve the conflict? If possible, I would appreciate it if you could submit the updated changes by today.

I will check the PR later today, and if everything looks good, I will proceed with merging it.

Thanks again for your contribution!

**Comment by PairZhu** [comment]
https://github.com/CVHub520/X-AnyLabeling/blob/23578d9821c35a4b74bbdb1990a52ab6d65f4cfb/anylabeling/views/labeling/label_widget.py#L3473
What does this line of code do? The Checked state should be switched automatically when the event is triggered

**Comment by CVHub520** [comment]
> https://github.com/CVHub520/X-AnyLabeling/blob/23578d9821c35a4b74bbdb1990a52ab6d65f4cfb/anylabeling/views/labeling/label_widget.py#L3473
> 
> 
> What does this line of code do? The Checked state should be switched automatically when the event is triggered @CVHub520

The line of code you've posted:
```python
self.actions.save_with_image_data.setChecked(enabled)
```
is intended to set the checked state of the "save_with_image_data" action based on the `enabled` parameter. This effectively triggers the operation to either save or not save the image data when the corresponding action is performed.

However, you are correct in pointing out that there seems to be a missing step. To ensure that the configuration is actually saved after modifying it, you should include the following line of code:

```python
save_config(self._config)
```
This `save_config` function call is necessary to persist the changes to the configuration so that the "save with image data" setting is remembered across sessions.

Thanks for bringing this to our attention. If you add the `save_config` call after setting the checked state, it should work as expected.
```

**Comment by PairZhu** [comment]
> > https://github.com/CVHub520/X-AnyLabeling/blob/23578d9821c35a4b74bbdb1990a52ab6d65f4cfb/anylabeling/views/labeling/label_widget.py#L3473
> > 
> > What does this line of code do? The Checked state should be switched automatically when the event is triggered @CVHub520
> 
> The line of code you've posted:
> 
> ```python
> self.actions.save_with_image_data.setChecked(enabled)
> ```
> 
> is intended to set the checked state of the "save_with_image_data" action based on the `enabled` parameter. This effectively triggers the operation to either save or not save the image data when the corresponding action is performed.
> 
> However, you are correct in pointing out that there seems to be a missing step. To ensure that the configuration is actually saved after modifying it, you should include the following line of code:
> 
> ```python
> save_config(self._config)
> ```
> 
> This `save_config` function call is necessary to persist the changes to the configuration so that the "save with image data" setting is remembered across sessions.
> 
> Thanks for bringing this to our attention. If you add the `save_config` call after setting the checked state, it should work as expected.

There is no need to save the configuration file once for all operations, I fixed the call to closeEvent and can write the configuration file when closing the application

**Review by CVHub520 — COMMENTED** [review]
LGTM! I've reviewed the changes and everything looks good. No issues found. I'll go ahead and merge this PR. Great work, and thanks for the contribution!

👍️ Approved and ready to merge.

**Pull request merged**
