### PR TITLE
Add action to loop through each label. When clicked they are centred in view

### PR DESCRIPTION
**Pull request by julianstirling**
This PR is to add the feature discussed in [this discussion](https://github.com/CVHub520/X-AnyLabeling/discussions/643)

### CODE REVIEW

**Comment by CVHub520** [comment]
Hi Julian,

Thanks for submitting this PR to add the label looping feature we discussed. It's a great addition that will definitely improve the user experience.

I’ve been testing it out, and while it works brilliantly for most shape types, I’ve run into a small snag when dealing with point annotations. I’ve already detailed the specific issue in the code review comments; you can refer to them for more information.

Would you mind updating the PR to handle this edge case? If you need a hand or want to bounce around any ideas, just give me a shout. Cheers for your work on this!

**Comment by julianstirling** [comment]
> I’ve already detailed the specific issue in the code review comments; you can refer to them for more information.

Hi @CVHub520 I don't see comments in the code review tab. Did you submit the review?

**Review by CVHub520 — CHANGES_REQUESTED** [review]
It seems we're getting a division by zero error in these cases. Here's the traceback:

```
Traceback (most recent call last):
  File "/home/cvhub/workspace/projects/python/toolkits/X-AnyLabeling/./anylabeling/views/labeling/label_widget.py", line 2558, in loop_thru_labels
    zoom = int(100*width / (3*label_width))
ZeroDivisionError: float division by zero
```

This happens because for point annotations, both `label_width` and `label_height` end up being 0, which leads to the division by zero when calculating the zoom.

I reckon we could sort this out by adding a quick check before the zoom calculation. Something like this might do the trick:

```python
if label_width == 0 or label_height == 0:
    # For point annotations, use a fixed zoom level or skip zooming
    zoom = 100  # or another suitable default value
else:
    zoom = int(100*width / (3*label_width))
```

It might be worth adding similar checks wherever we're using `label_width` and `label_height`, just to make the code a bit more robust.

**Comment by CVHub520** [comment]
Hi @julianstirling,

Yes, I’ve submitted my code review comments. They should now be visible in the code review tab for your reference.

**Comment by julianstirling** [comment]
Hi @ CV hub,

I have just set a minimum when calculating `label_width`. `label_height` is no longer needed as we calculate a zoom factor and and use this to get the scroll bars bang on (Thanks to @quitmeyer). I also now check that the zoom is not above 1000, as this is the maximum it can be set to.

This seems to work nicely with points.

**Comment by julianstirling** [comment]
@CVHub520 Tagging you again as somehow I messed it up above!

**Review by CVHub520 — APPROVED** [review]
LGTM

**Comment by CVHub520** [comment]
It's great to hear that these changes are working well with points. Your attention to detail in optimizing the calculations and adding safeguards is valuable.

I've approved and merged your changes. Thanks again for your work on this!

**Pull request merged**
